Devise authntication
erezfree29/Authentication pull request #2
Opened 2021-04-21 13:39 UTC by erezfree29

created a members-only app using the devise gem which includes 

-User sign up with a secure password
-User sign in
-User sign-up validations(user creation)
-Post creation only for signed-up users.
-Post validations on creating.
-Restricted access to post creation only to logged-in users.
-Access to post-index where all the posts are shown.
-Posts Authors are only displayed if a user is signed in.

2021-04-21 17:30 UTC, BrianSammit requested changes
CHANGES REQUIRED :red_circle: 
-------------------
Hello @erezfree29  You did an amazing job so far :+1: :clap: 

TO HIGHLIGHT: 
- Your app is working properly. 
- Your repository is professional.
- Your Project is professional
- I like that the password must be difficult so is difficult to know the password. 

However, there are a few changes to make to complete this project :hammer_and_wrench: see them below :eyes: :point_down: 
--------------------
- [ ] Please check the step on how to clone the repo. You write `cd re-form` and it must be `cd Authentication`
- [ ] The issue link is not working. 
- [ ] Please add steps on your readme on how to start the project. E.g `rails server or rails s` and `http://localhost:3000/` 
- [ ] Please check the title of your pull request you misspell authentication. 
- [ ] Please don't use logic in your views instead put the logic on helpers. [Here](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) you can read about how to put your logic on helpers. 

<img width="825" alt="no_logic_in_helpers_requirement" src="https://user-images.githubusercontent.com/64173189/115592950-803b5480-a299-11eb-840b-4745e53471cf.png">

- [ ] Please add a sign-in link on post views. 

![sign_in_out_link_requirement](https://user-images.githubusercontent.com/64173189/115593539-3a32c080-a29a-11eb-9db7-37d8dd1605b3.png)

- [ ] On your routes, please scope only the routes you need. E.g `resources :posts, only: [:new, :create, :index]`.
- [ ] Please write the sign in and sign out in `application.html.erb` that is inside the `layouts` folder so you don't need to manually repeat it in every view. 
------------
Make these required changes and send it again for another review. 
Reachme on SLACK if you have any questions about the requirements. 
@ Brian Sammit Cruz Rodriguez
HAPPY CODING!!

![200 (1)](https://user-images.githubusercontent.com/64173189/115596138-5edc6780-a29d-11eb-9459-23dccabc617f.gif)

2021-04-22 10:26 UTC, mimipeshy commented
## STATUS: CHANGES REQUESTED 🔴 ♻️ 
Hello, @erezfree29 👋🏾 this is a great job you have done in this milestone. You have worked on the TSE comments which is commendable. However, before approval, let's fix the following ⬇️ 

- [ ]  Kindly remove logic from your views. Logic includes loops and if statements. This will ensure your project follows the MVC pattern. You can create all your logic inside the helpers.  Read about [helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)


That's all 😄, kindly submit another review when done
If you need any clarification, kindly post your comment here and tag me @mimipeshy and will be glad to help

Regards,
Peris Ndanu

2021-04-22 10:27 UTC, mimipeshy commented on app/views/posts/index.html.erb
> +</ul>
Ensure there is absolutely no logic in your views

2021-04-22 12:25 UTC, oloomoses approved these changes
# Congratulations, Project Approved. :muscle: :tada: :clap: 
**Great job working on the suggested changes from the previous review.
You have passed all the requirements for this project :muscle: 
Feel free to merge and close this pull request.**

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

2021-04-23 11:52 UTC, merged